### ISSUE TITLE
clearWatch

### ISSUE THREAD

**Issue by dailycommit** [itinance/redux-saga-location#6]
Apparently **clearWatch** (``navigator.geolocation.clearWatch``) function is missing, How do I stop **watchCurrentPosition** ?

**Comment by webraptor** [comment]
@dailycommit this should now be available under version 1.6.0

**Comment by itinance** [comment]
It's done with latest release 1.6.0 thanks to this PR https://github.com/itinance/redux-saga-location/pull/19 by @webraptor 

I am going to close this issue. Pls reopen if necessary
